---
version: "3.3"
services:
  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.7.1
    ports:
     - "9090:9090"
    networks:
     - internal
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/clients.json:/prometheus/servicediscovery/clients.json
    links:
      - proxy

  proxy:
    hostname: proxy
    build: .
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
     - "8080:8080"
    environment:
      - "RUN_MODE=server"
      - "SERVER_LOG_LEVEL=debug"
    networks:
     - internal

  client:
    build: .
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - "RUN_MODE=client"
      - "CLIENT_PROXY_URL=http://proxy:8080"
      - "CLIENT_HEARTBEAT=10s"
      - "CLIENT_REMOTE_FQDN=sample_app"
      - "CLIENT_LOG_LEVEL=info"
    links:
      - proxy
    networks:
     - internal

  sample_app:
    hostname: app
    image: quay.io/brancz/prometheus-example-app:v0.1.0
    restart: always
    links:
      - client
    networks:
      - internal


networks:
  internal:
    attachable: true
    ipam:
      config:
        - subnet: 172.10.0.0/16
